global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: identityservice
    metrics_path: /metrics
    static_configs:
      - targets: ["identityservice:5000"]

  - job_name: courseservice
    metrics_path: /metrics
    static_configs:
      - targets: ["courseservice:5001"]

  - job_name: learningservice
    metrics_path: /metrics
    static_configs:
      - targets: ["learningservice:5002"]

  - job_name: notificationservice
    metrics_path: /metrics
    static_configs:
      - targets: ["notificationservice:5003"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
