<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LearningService.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LearningService.Domain\LearningService.Domain.csproj" />
    <ProjectReference Include="..\..\..\shared\Platform.Contracts\src\Platform.Contracts\Platform.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\Platform.Common\src\Platform.Common\Platform.Common.csproj" />
  </ItemGroup>

</Project>
